#!/bin/sh

# Install this first!!
# $ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# Then chmod +x this file, put it in /usr/bin

# add more args here according to preference
ARGS="--volume=100"

notification(){
# change the icon to whatever you want. Make sure your notification server 
# supports it and already configured.

# Now it will receive argument so the user can rename the radio title
# to whatever they want

	notify-send -t 3000 "Streaming " "$@"
}

menu(){
	printf "1. Lofi Girl\n"
	printf "2. Chillhop\n"
	printf "3. Box Lofi\n"
	printf "4. The Bootleg Boy\n"
	printf "5. Radio Spinner\n"
	printf "6. SmoothChill\n"
	printf "7. HeartDance\n"
	printf "8. HeartLove\n"
	printf "9. SmoothCountry\n"
	printf "10. SmoothRelax\n"
	printf "11. SmoothUK\n"
	printf "12. SmoothLondon\n"
	printf "13. RadioX00s\n"
	printf "14. RadioX90s\n"
	printf "15. RadioXChilled\n"
}

main() {
	choice=$(menu | wofi -dmenu | cut -d. -f1)

	case $choice in
		1)
			notification "Lofi Girl";
            URL="https://play.streamafrica.net/lofiradio"
			break
			;;
		2)
			notification "Chillhop";
            URL="http://stream.zeno.fm/fyn8eh3h5f8uv"
			break
			;;
		3)
			notification "Box Lofi";
            URL="http://stream.zeno.fm/f3wvbbqmdg8uv"
			break
			;;
		4)
			notification "The Bootleg Boy";
            URL="http://stream.zeno.fm/0r0xa792kwzuv"
			break
			;;
		5)
			notification "Radio Spinner";
            URL="https://live.radiospinner.com/lofi-hip-hop-64"
			break
			;;
		6)
			notification "SmoothChill";
            URL="https://media-ssl.musicradio.com/SmoothChill"
			break
			;;
		7)
			notification "HeartDance";
            URL="https://media-ssl.musicradio.com/HeartDanceMP3"
			break
			;;
		8)
			notification "HeartLove";
            URL="https://media-ssl.musicradio.com/HeartLoveMP3"
			break
			;;
		9)
			notification "SmoothCountry";
            URL="https://media-ssl.musicradio.com/SmoothCountry"
			break
			;;
		10)
			notification "SmoothRelax";
            URL="https://media-ssl.musicradio.com/SmoothRelax"
			break
			;;
		11)
			notification "SmoothUK";
            URL="https://media-ssl.musicradio.com/SmoothUK"
			break
			;;
		12)
			notification "SmoothLondon";
            URL="https://media-ssl.musicradio.com/SmoothLondonMP3"
			break
			;;
		13)
			notification "RadioX00s";
            URL="https://media-ssl.musicradio.com/RadioX00s"
			break
			;;
		14)
			notification "RadioX90s";
            URL="https://media-ssl.musicradio.com/RadioX90s"
			break
			;;
		15)
			notification "RadioXChilled";
            URL="https://media-ssl.musicradio.com/RadioXChilled"
			break
			;;
	esac
    # run mpv with args and selected url
    # added title arg to make sure the pkill command kills only this instance of mpv
    mpv $ARGS --title="radio-mpv" $URL
}

pkill -f radio-mpv || main
