# Path to Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"

# Theme: Powerlevel10k (install via AUR or git)
ZSH_THEME="powerlevel10k/powerlevel10k"

# Plugins
plugins=(
  git
  z
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# Hyprland & Wayland env
export XDG_SESSION_TYPE=wayland
export WAYLAND_DISPLAY=wayland-0

# Prompt tweaks
[[ ! -f ~/.p10k.zsh ]] && exec p10k configure
source ~/.p10k.zsh

alias ls='exa'
alias l='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'

# alias cd='z'

alias install='sudo pacman -S --noconfirm --needed'
alias uninstall='sudo pacman -Rns'
alias upgrade='sudo pacman -Syu --noconfirm'

alias sayonara='poweroff'
alias rebirth='reboot'
alias quicknap='suspend'
